services:
  postgresql:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=my-crud-db